- id: '1592466029585'
  alias: Matt arrived at work
  description: ''
  trigger:
  - entity_id: device_tracker.matts_iphone
    event: enter
    platform: zone
    zone: zone.matt_work
  condition: []
  action:
  - data:
      message: Matt has arrived at work :)
    service: notify.mobile_app_amys_iphone
- id: '1592466090508'
  alias: Matt left work
  description: ''
  trigger:
  - entity_id: device_tracker.matts_iphone
    event: leave
    platform: zone
    zone: zone.matt_work
  condition: []
  action:
  - data:
      message: Matt is on his way home!
    service: notify.mobile_app_amys_iphone
- id: '1593613973496'
  alias: New Podcast Notification
  description: ''
  trigger:
  - event_data: {}
    event_type: feedreader
    platform: event
  condition: []
  action:
  - data:
      message: '{{trigger.event.data.title}}'
      title: New Podcast Available
    service: notify.mobile_app_matts_iphone
- id: '1595276636180'
  alias: Turn off Jasper Bedlight in the morning.
  description: ''
  trigger:
  - above: 10
    device_id: 1769986992614a27a48273fbcec4225c
    domain: sensor
    entity_id: sensor.lightlevel_16
    platform: device
    type: illuminance
  condition:
  - after: 06:00
    condition: time
  action:
  - data: {}
    entity_id: light.wled
    service: light.turn_off
- id: '1595276723291'
  alias: Turn off Jasper bedlight at night
  description: ''
  trigger:
  - below: 2
    device_id: 1769986992614a27a48273fbcec4225c
    domain: sensor
    entity_id: sensor.lightlevel_16
    platform: device
    type: illuminance
  condition:
  - after: '21:00'
    before: 05:30
    condition: time
  action:
  - data: {}
    entity_id: light.wled
    service: light.turn_off
- id: 40d5c9a9-91e3-495b-bb00-479e0ddd404b
  alias: Tumble Dryer finished
  initial_state: true
  trigger:
    platform: template
    value_template: '{{ states(''sensor.tumble_dryer_switch_watts'') | int < 10 }}'
    for:
      seconds: 90
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.living_room_mini
      volume_level: 0.5
  - delay:
      seconds: 2
  - service: tts.google_translate_say
    entity_id: media_player.living_room_mini
    data_template:
      message: '{{ ["Your clothes are dry", "The tumble dryer has finished", "Go outside
        and empty the tumble dryer"] | random }}'
- id: 66760039-0bc1-4870-9e91-e65cb42ae180
  alias: Sensor offline
  trigger:
  - platform: event
    event_type: state_changed
  condition:
  - condition: template
    value_template: "{{\n  trigger.event.data.entity_id.startswith('sensor.') and\n\
      \  trigger.event.data.new_state is not none and\n  trigger.event.data.new_state.state\
      \ == 'unavailable' and\n  (\n    trigger.event.data.old_state is none or\n \
      \   trigger.event.data.old_state.state != 'unavailable'\n  )\n}}\n"
  action:
  - data_template:
      message: '{{ trigger.event.data.new_state.name }} is offline, please investigate'
      title: Sensor Offline
    service: notify.mobile_app_matts_iphone
- id: 22a9792f-9e19-49dd-8fb9-f7e3091cae9f
  alias: Light offline
  trigger:
  - event_type: state_changed
    platform: event
  condition:
  - condition: template
    value_template: "{{\n  trigger.event.data.entity_id.startswith('light.') and\n\
      \  trigger.event.data.new_state is not none and\n  trigger.event.data.new_state.state\
      \ == 'unavailable' and\n  (\n    trigger.event.data.old_state is none or\n \
      \   trigger.event.data.old_state.state != 'unavailable'\n  )\n}}\n"
  action:
  - data_template:
      message: '{{ trigger.event.data.new_state.name }} is offline, please investigate'
      title: Light Offline
    service: notify.mobile_app_matts_iphone
- id: '1595536688939'
  alias: Sonarr Download
  description: ''
  trigger:
  - platform: webhook
    webhook_id: thWIZPYvA6SJ9T2TQj6l7e2QbNcYQbBk
  condition: []
  action:
  - data_template:
      message: '{{ trigger.json }}'
    service: notify.mobile_app_matts_iphone
