- id: '1592466029585'
  alias: Matt arrived at work
  description: ''
  trigger:
  - entity_id: device_tracker.matts_iphone
    event: enter
    platform: zone
    zone: zone.matt_work
  condition: []
  action:
  - data:
      message: Matt has arrived at work :)
    service: notify.mobile_app_amys_iphone
- id: '1592466090508'
  alias: Matt left work
  description: ''
  trigger:
  - entity_id: device_tracker.matts_iphone
    event: leave
    platform: zone
    zone: zone.matt_work
  condition: []
  action:
  - data:
      message: Matt is on his way home!
    service: notify.mobile_app_amys_iphone
- id: '1593613973496'
  alias: New Podcast Notification
  description: ''
  trigger:
  - event_data: {}
    event_type: feedreader
    platform: event
  condition: []
  action:
  - data:
      message: '{{trigger.event.data.title}}'
      title: New Podcast Available
    service: notify.mobile_app_matts_iphone
- id: 40d5c9a9-91e3-495b-bb00-479e0ddd404b
  alias: Tumble Dryer finished
  initial_state: true
  trigger:
    platform: template
    value_template: '{{ states(''sensor.tumble_dryer_switch_watts'') | int < 200 }}'
    for:
      seconds: 120
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.living_room_mini
      volume_level: 0.5
  - delay:
      seconds: 2
  - service: tts.google_cloud_say
    entity_id: media_player.living_room_mini
    data_template:
      message: '{{ ["Your clothes are dry", "The tumble dryer has finished", "Go outside
        and empty the tumble dryer"] | random }}'
- id: '1593348724453'
  alias: Notification on HACS update
  description: ''
  trigger:
  - above: '0'
    entity_id: sensor.hacs
    for: '600'
    platform: numeric_state
  condition: []
  action:
  - data:
      message: HACS reports updated repositories available.
      title: HACS Update(s) Available.
    service: notify.mobile_app_matts_iphone
  mode: single
- id: '1596048053090'
  alias: Jasper Door Close
  description: ''
  trigger:
  - device_id: 5ef3262dd4b544d68ed261b1a36a03de
    domain: binary_sensor
    entity_id: binary_sensor.openclose_22
    platform: device
    type: not_opened
  condition:
  - after: '20:30'
    condition: time
  action:
  - data: {}
    entity_id: light.wled
    service: light.turn_off
  - data: {}
    entity_id: light.cubby_light
    service: light.turn_off
  - data: {}
    entity_id: input_boolean.hall_motion_bypass
    service: input_boolean.turn_off
  mode: single
- id: '1596048131147'
  alias: Jasper Door Open
  description: ''
  trigger:
  - device_id: 5ef3262dd4b544d68ed261b1a36a03de
    domain: binary_sensor
    entity_id: binary_sensor.openclose_22
    for:
      hours: 0
      minutes: 5
      seconds: 0
    platform: device
    type: opened
  condition:
  - after: 06:00
    before: 08:00
    condition: time
  action:
  - data: {}
    entity_id: light.wled
    service: light.turn_off
  mode: single
- id: '1596134844590'
  alias: morning
  description: ''
  trigger:
  - entity_id: binary_sensor.presence_15
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: media_player.kitchen_display
      media_content_id: https://ais.absoluteradio.co.uk/absoluteradiohigh.aac?direct=true&listenerid=undefined&aw_0_1st.bauer_listenerid=undefined&amsparams=playerid:BMUK_html5;skey:1593897078;&aw_0_1st.playerid=BMUK_html5&aw_0_1st.skey=1593897078&aw_0_1st.bauer_loggedin=false&awparams=loggedin:false;&aw_0_req.userConsent=BO2CRb-O2CRb-AGABBENDR-AAAAwx7_______9______9uz_Ov_v_f__33e8__9v_l_7_-___u_-33d4-_1vf99yfm1-7ftr3tp_87ues2_Xur__79__3z3_9pxP78k89r7337Mw_v-_v-b7JCPN_Y3v-8K96lGA
      media_content_type: audio/mp4
    service: media_player.play_media
  mode: single
