# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml

frontend:
  themes: !include_dir_merge_named themes

media_player:
  - platform: androidtv
    name: ShieldTV
    host: 192.168.68.103
    adb_server_ip: 127.0.0.1
  - platform: androidtv
    name: Bedroom FireStick
    host: 192.168.68.105
    adb_server_ip: 127.0.0.1
  - platform: channels
    name: Shield
    host: 192.168.68.103
  - platform: channels
    name: Bedroom
    host: 192.168.68.105
  - platform: spotify_metafy
    users:
      spotify_entity_id: media_player.spotify_matt
      destination: Kitchen Display
      playlists:
      - uri: spotify:playlist:37i9dQZF1CAaiIWVF9iQy0
    
cloudflare:
  email: !secret cloudfare_email
  api_key: !secret cloudfare_apikey
  zone: !secret cloudfare_zone
  records:
    - !secret cloudfare_zone

homeassistant:
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
       - 127.0.0.1
       - 192.168.68.0/24
     allow_bypass_login: true

badnest:
  issue_token: !secret badnest_token
  cookie: !secret badnest_cookie
  region: uk

climate:
  - platform: badnest
    scan_interval: 10

notify:
  - platform: nfandroidtv
    name: shield
    host: 192.168.68.103

esphome:

device_tracker:
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password
  - platform: mqtt
    devices:
      mattsiphone: 'monitor/monitorpi/matts_iphone/device_tracker'
      amysiphone: 'monitor/monitorpi/amys_iphone/device_tracker'
  - platform: mqtt
    devices:
      amyiphone: 'monitor/officemonitor/amys_iphone/device_tracker'
      mattiphone: 'monitor/officemonitor/matts_iphone/device_tracker'

pi_hole:
  - host: 192.168.68.106
    api_key: !secret pihole_apikey

zone: 
  - name: Home
    latitude: 51.402343
    longitude: -0.756625
    radius: 25
    icon: mdi:home

google:
  client_id: !secret googleclient_id
  client_secret: !secret googleclient_secret

recorder:
  db_url: !secret mariadb_link

speedtestdotnet:
  scan_interval:
    days: 1
  monitored_conditions:
  - ping
  - download
  - upload

remote:
  - platform: broadlink
    host: 192.168.68.130
    mac: 24-DF-A7-7A-A6-53
    type: rm_mini3_redbean

browser_mod:

monitor_docker:
  - name: Docker
    containers:
      - plex
      - code-server
      - iCloudPD-matt
      - docker_bitwarden_1
      - home-assistant
      - docker_esphome_1
      - node-red
      - docker_monitoring_1
      - letsencrypt
      - mosquitto
      - adbd
      - tautulli
      - phpmyadmin
      - bazarr
      - ombi
      - nzbget
      - portainer
      - channels-dvr
      - sonarr
      - mariadb
      - radarr
    rename:
      docker_bitwarden_1: Bitwarden 
      docker_esphome_1: ESPhome
      docker_monitoring_1: Glances
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - containers_cpu_percentage
      - containers_memory
      - containers_memory_percentage
      - status
      - memory
      - cpu_percentage
      - memory_percentage

spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_clientsecret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  
