title: Bridge Manor
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.remote_ui
      - entity: binary_sensor.hallway_sensor
      - entity: binary_sensor.wardrobe_sensor
      - entity: binary_sensor.window_door_sensor
      - entity: binary_sensor.updater
      - entity: binary_sensor.hassio_config_check
      - entity: binary_sensor.icloud_rsync
      - entity: binary_sensor.monitor_pi
      - entity: binary_sensor.phoscon_pi
      - entity: binary_sensor.wireguard_pi
      - entity: binary_sensor.docker_rsync
      - entity: binary_sensor.button
      - entity: binary_sensor.synology_security_status
      - entity: binary_sensor.synology_drive_1_exceeded_max_bad_sectors
      - entity: binary_sensor.synology_drive_1_below_min_remaining_life
      - entity: binary_sensor.synology_drive_2_exceeded_max_bad_sectors
      - entity: binary_sensor.synology_drive_2_below_min_remaining_life
      - entity: person.matt_bridges
      - entity: sensor.time
      - entity: sensor.date
      - entity: sensor.installed_version
      - entity: sensor.plex_memory_average
      - entity: sensor.plex_cpu_average
      - entity: sensor.icloudpd_memory_average
      - entity: sensor.icloudpd_cpu_average
      - entity: sensor.sonarr_memory_average
      - entity: sensor.sonarr_cpu_average
      - entity: sensor.radarr_memory_average
      - entity: sensor.radarr_cpu_average
      - entity: sensor.nzbget_memory_average
      - entity: sensor.nzbget_cpu_average
      - entity: sensor.bazarr_memory_average
      - entity: sensor.bazarr_cpu_average
      - entity: sensor.channelsdvr_memory_average
      - entity: sensor.channelsdvr_cpu_average
      - entity: sensor.ombi_memory_average
      - entity: sensor.ombi_cpu_average
      - entity: sensor.letsencrypt_memory_average
      - entity: sensor.letsencrypt_cpu_average
      - entity: sensor.ha_dockermon_memory_average
      - entity: sensor.ha_dockermon_cpu_average
      - entity: sensor.bitwarden_memory_average
      - entity: sensor.bitwarden_cpu_average
      - entity: sensor.homeassistant_memory_average
      - entity: sensor.homeassistant_cpu_average
      - entity: sensor.glances_memory_average
      - entity: sensor.glances_cpu_average
      - entity: sensor.nodered_memory_average
      - entity: sensor.nodered_cpu_average
      - entity: sensor.mosquitto_memory_average
      - entity: sensor.mosquitto_cpu_average
      - entity: sensor.adbd_memory_average
      - entity: sensor.adbd_cpu_average
      - entity: sensor.codeserver_memory_average
      - entity: sensor.codeserver_cpu_average
      - entity: sensor.esphome_memory_average
      - entity: sensor.esphome_cpu_average
      - entity: sensor.tautulli_memory_average
      - entity: sensor.tautulli_cpu_average
      - entity: sensor.mariadb_memory_average
      - entity: sensor.mariadb_cpu_average
      - entity: sensor.speedtest_lastrun
      - entity: sensor.myip
      - entity: sensor.phosconpi_system_cpu
      - entity: sensor.phosconpi_system_ram
      - entity: sensor.plex_status
      - entity: sensor.latest_available_version
      - entity: sensor.icloudpd_status
      - entity: sensor.sonarr_status
      - entity: sensor.nzbget_status
      - entity: sensor.radarr_status
      - entity: sensor.bazarr_status
      - entity: sensor.channels_dvr_status
      - entity: sensor.ombi_status
      - entity: sensor.linux_server_uptime
      - entity: sensor.letsencrypt_status
      - entity: sensor.ha_dockermon_status
      - entity: sensor.bitwarden_status
      - entity: sensor.home_assistant_status
      - entity: sensor.node_red_status
      - entity: sensor.glances_status
      - entity: sensor.mosquitto_status
      - entity: sensor.code_server_status
      - entity: sensor.tautulli_status
      - entity: sensor.esphome_status
      - entity: sensor.android_debug_bridge_status
      - entity: sensor.mariadb_status
      - entity: sensor.plex_memory
      - entity: sensor.nzbget_memory
      - entity: sensor.ha_dockermon_memory
      - entity: sensor.ha_dockermon_cpu
      - entity: sensor.nzbget_cpu
      - entity: sensor.sonarr_memory
      - entity: sensor.sonarr_cpu
      - entity: sensor.radarr_memory
      - entity: sensor.radarr_cpu
      - entity: sensor.bazarr_cpu
      - entity: sensor.bazarr_memory
      - entity: sensor.plex_cpu
      - entity: sensor.ombi_memory
      - entity: sensor.icloudpd_cpu
      - entity: sensor.ombi_cpu
      - entity: sensor.channels_dvr_cpu
      - entity: sensor.icloudpd_memory
      - entity: sensor.channels_dvr_memory
      - entity: sensor.letsencrypt_memory
      - entity: sensor.letsencrypt_cpu
      - entity: sensor.home_assistant_cpu
      - entity: sensor.bitwarden_memory
      - entity: sensor.home_assistant_memory
      - entity: sensor.bitwarden_cpu
      - entity: sensor.esphome_cpu
      - entity: sensor.esphome_memory
      - entity: sensor.tautulli_cpu
      - entity: sensor.tautulli_memory
      - entity: sensor.mariadb_cpu
      - entity: sensor.mariadb_memory
      - entity: sensor.node_red_cpu
      - entity: sensor.android_debug_bridge_memory
      - entity: sensor.android_debug_bridge_cpu
      - entity: sensor.glances_memory
      - entity: sensor.glances_cpu
      - entity: sensor.node_red_memory
      - entity: sensor.mosquitto_memory
      - entity: sensor.mosquitto_cpu
      - entity: sensor.code_server_memory
      - entity: sensor.code_server_cpu
      - entity: sensor.general_waste
      - entity: sensor.recycling_and_garden_waste
      - entity: sensor.transmitter_battery_level
      - entity: sensor.hallway_sensor_battery_level
      - entity: sensor.hallway_sensor
      - entity: sensor.hallway_sensor_2
      - entity: sensor.dimmer_switch_battery_level
      - entity: sensor.wardrobe_sensor_battery_level
      - entity: sensor.wardrobe_sensor
      - entity: sensor.wardrobe_sensor_2
      - entity: sensor.window_door_sensor_battery_level
      - entity: sensor.smart_switch_battery_level
      - entity: sensor.mi_magic_cube_battery_level
      - entity: sensor.pi_hole_ads_blocked_today
      - entity: sensor.pi_hole_ads_percentage_blocked_today
      - entity: sensor.pi_hole_seen_clients
      - entity: sensor.pi_hole_dns_queries_today
      - entity: sensor.pi_hole_domains_blocked
      - entity: sensor.pi_hole_dns_queries_cached
      - entity: sensor.pi_hole_dns_queries_forwarded
      - entity: sensor.pi_hole_dns_unique_clients
      - entity: sensor.pi_hole_dns_unique_domains
      - entity: sensor.glances_etc_resolv_conf_used_percent_2
      - entity: sensor.glances_etc_hostname_used_percent_2
      - entity: sensor.glances_etc_hosts_used_percent_2
      - entity: sensor.glances_etc_resolv_conf_used_2
      - entity: sensor.glances_etc_hostname_used_2
      - entity: sensor.glances_etc_hosts_used_2
      - entity: sensor.glances_etc_resolv_conf_free_2
      - entity: sensor.glances_etc_hostname_free_2
      - entity: sensor.glances_etc_hosts_free_2
      - entity: sensor.glances_ram_used_percent
      - entity: sensor.glances_ram_used
      - entity: sensor.glances_ram_free
      - entity: sensor.glances_swap_used_percent
      - entity: sensor.glances_swap_used
      - entity: sensor.glances_swap_free
      - entity: sensor.glances_cpu_load
      - entity: sensor.glances_running
      - entity: sensor.glances_total
      - entity: sensor.glances_thread
      - entity: sensor.glances_sleeping
      - entity: sensor.glances_cpu_used
      - entity: sensor.glances_package_id_0_temp
      - entity: sensor.glances_core_0_temp
      - entity: sensor.glances_core_1_temp
      - entity: sensor.glances_ta0p_temp
      - entity: sensor.glances_tc0f_temp
      - entity: sensor.glances_tc0g_temp
      - entity: sensor.glances_tc0j_temp
      - entity: sensor.glances_tc0p_temp
      - entity: sensor.glances_tc0c_temp
      - entity: sensor.glances_tc0p_temp_2
      - entity: sensor.glances_tc1c_temp
      - entity: sensor.glances_tc1c_temp_2
      - entity: sensor.glances_tcgc_temp
      - entity: sensor.glances_tcgc_temp_2
      - entity: sensor.glances_ta0v_temp
      - entity: sensor.glances_tcpg_temp
      - entity: sensor.glances_tcsc_temp
      - entity: sensor.glances_tcsc_temp_2
      - entity: sensor.glances_tctd_temp
      - entity: sensor.glances_tcxc_temp
      - entity: sensor.glances_tcxc_temp_2
      - entity: sensor.glances_tcxr_temp
      - entity: sensor.glances_th0a_temp
      - entity: sensor.glances_th0b_temp
      - entity: sensor.glances_th0c_temp
      - entity: sensor.glances_ta0p_temp_2
      - entity: sensor.glances_th0f_temp
      - entity: sensor.glances_th0o_temp
      - entity: sensor.glances_th0p_temp
      - entity: sensor.glances_th0r_temp
      - entity: sensor.glances_th0a_temp_2
      - entity: sensor.glances_th0b_temp_2
      - entity: sensor.glances_th0c_temp_2
      - entity: sensor.glances_th1a_temp
      - entity: sensor.glances_th1b_temp
      - entity: sensor.glances_th1c_temp
      - entity: sensor.glances_ta1p_temp
      - entity: sensor.glances_th1f_temp
      - entity: sensor.glances_th1o_temp
      - entity: sensor.glances_th1p_temp
      - entity: sensor.glances_th1r_temp
      - entity: sensor.glances_th1a_temp_2
      - entity: sensor.glances_th1b_temp_2
      - entity: sensor.glances_th1c_temp_2
      - entity: sensor.glances_tm0p_temp
      - entity: sensor.glances_tm0v_temp
      - entity: sensor.glances_tm0p_temp_2
      - entity: sensor.glances_ta1p_temp_2
      - entity: sensor.glances_tpcd_temp
      - entity: sensor.glances_tpcd_temp_2
      - entity: sensor.glances_ts0v_temp
      - entity: sensor.glances_tw0p_temp
      - entity: sensor.glances_tw0p_temp_2
      - entity: sensor.glances_te0t_temp
      - entity: sensor.glances_te0t_temp_2
      - entity: sensor.glances_tm0p_temp_3
      - entity: sensor.glances_tm0p_temp_4
      - entity: sensor.glances_tp0c_temp
      - entity: sensor.glances_ta2p_temp
      - entity: sensor.glances_ts0g_temp
      - entity: sensor.glances_ta2p_temp_2
      - entity: sensor.glances_tc0c_temp_2
      - entity: sensor.glances_tc0e_temp
      - entity: sensor.matts_iphone_activity
      - entity: sensor.matts_iphone_battery_level
      - entity: sensor.matts_iphone_battery_state
      - entity: sensor.matts_iphone_bssid
      - entity: sensor.matts_iphone_connection_type
      - entity: sensor.matts_iphone_sim_1
      - entity: sensor.matts_iphone_ssid
      - entity: sensor.matts_iphone_geocoded_location
      - entity: sensor.matts_iphone_last_update_trigger
      - entity: sensor.matts_iphone_average_active_pace
      - entity: sensor.matts_iphone_distance
      - entity: sensor.matts_iphone_floors_ascended
      - entity: sensor.matts_iphone_floors_descended
      - entity: sensor.matts_iphone_steps
      - entity: sensor.synology_cpu_load_other_2
      - entity: sensor.synology_cpu_load_user_2
      - entity: sensor.synology_cpu_load_system_2
      - entity: sensor.synology_cpu_load_total_2
      - entity: sensor.synology_cpu_load_1_min_2
      - entity: sensor.synology_cpu_load_5_min_2
      - entity: sensor.synology_cpu_load_15_min_2
      - entity: sensor.synology_memory_usage_real_2
      - entity: sensor.synology_memory_size_2
      - entity: sensor.synology_memory_cached_2
      - entity: sensor.synology_memory_available_swap_2
      - entity: sensor.synology_memory_available_real_2
      - entity: sensor.synology_memory_total_swap_2
      - entity: sensor.synology_memory_total_real_2
      - entity: sensor.synology_network_up_2
      - entity: sensor.synology_network_down_2
      - entity: sensor.synology_status_volume_2_2
      - entity: sensor.synology_type_volume_2
      - entity: sensor.synology_total_size_volume_2_2
      - entity: sensor.synology_used_space_volume_2_2
      - entity: sensor.synology_volume_used_volume_2_2
      - entity: sensor.synology_average_disk_temp_volume_2_2
      - entity: sensor.synology_maximum_disk_temp_volume_2_2
      - entity: sensor.synology_name_sda
      - entity: sensor.synology_device_sda
      - entity: sensor.synology_status_smart_sda_2
      - entity: sensor.synology_status_sda_2
      - entity: sensor.synology_exceeded_max_bad_sectors_sda_2
      - entity: sensor.synology_below_min_remaining_life_sda_2
      - entity: sensor.synology_temperature_sda_2
      - entity: sensor.synology_name_sdb
      - entity: sensor.synology_device_sdb
      - entity: sensor.synology_status_smart_sdb_2
      - entity: sensor.synology_status_sdb_2
      - entity: sensor.synology_exceeded_max_bad_sectors_sdb_2
      - entity: sensor.synology_below_min_remaining_life_sdb_2
      - entity: sensor.synology_temperature_sdb_2
      - entity: sensor.hacs
      - entity: sensor.cert_expiry_bridgemanor_co_uk
      - entity: sensor.speedtest_ping
      - entity: sensor.speedtest_download
      - entity: sensor.speedtest_upload
      - entity: sensor.voltage
      - entity: sensor.current
      - entity: sensor.power
      - entity: sensor.m5_b_sent
      - entity: sensor.m5_packets_received
      - entity: sensor.m5_packets_sent
      - entity: sensor.m5_kib_s_received
      - entity: sensor.m5_kib_s_sent
      - entity: sensor.m5_packets_s_received
      - entity: sensor.m5_packets_s_sent
      - entity: sensor.m5_b_received
      - entity: sensor.wled_estimated_current
      - entity: sensor.synology_cpu_load_other
      - entity: sensor.synology_cpu_load_user
      - entity: sensor.synology_cpu_load_system
      - entity: sensor.synology_cpu_load_total
      - entity: sensor.synology_cpu_load_1_min
      - entity: sensor.synology_cpu_load_5_min
      - entity: sensor.synology_cpu_load_15_min
      - entity: sensor.synology_memory_usage_real
      - entity: sensor.synology_memory_size
      - entity: sensor.synology_memory_cached
      - entity: sensor.synology_memory_available_swap
      - entity: sensor.synology_memory_available_real
      - entity: sensor.synology_memory_total_swap
      - entity: sensor.synology_memory_total_real
      - entity: sensor.synology_network_up
      - entity: sensor.synology_network_down
      - entity: sensor.synology_status_volume_2
      - entity: sensor.synology_total_size_volume_2
      - entity: sensor.synology_used_space_volume_2
      - entity: sensor.synology_volume_used_volume_2
      - entity: sensor.synology_average_disk_temp_volume_2
      - entity: sensor.synology_maximum_disk_temp_volume_2
      - entity: sensor.synology_status_smart_sda
      - entity: sensor.synology_status_sda
      - entity: sensor.synology_exceeded_max_bad_sectors_sda
      - entity: sensor.synology_below_min_remaining_life_sda
      - entity: sensor.synology_temperature_sda
      - entity: sensor.synology_status_smart_sdb
      - entity: sensor.synology_status_sdb
      - entity: sensor.synology_exceeded_max_bad_sectors_sdb
      - entity: sensor.synology_below_min_remaining_life_sdb
      - entity: sensor.synology_temperature_sdb
      - entity: sensor.synology_drive_1_status
      - entity: sensor.synology_drive_2_status
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - calendar.family
          - calendar.garbage_collection
          - calendar.holidays_in_united_kingdom
          - calendar.holidays_in_the_united_states
          - calendar.matty_bridges_mb_gmail_com
        title: Calendar
      - type: thermostat
        entity: climate.living_room_thermostat
      - type: entities
        entities:
          - input_boolean.hall_motion_bypass
          - input_boolean.kitchen_catt
        title: Input boolean
      - type: entities
        entities:
          - input_select.gateway_color_mode
        title: Input select
      - type: entities
        entities:
          - light.bedroom
          - light.bedroom_light
          - light.bedside
          - light.bedside_light
          - light.cubby_light
          - light.hall
          - light.hall_light
          - light.living_room
          - light.unknown_6
          - light.wled
          - light.wardrobe
          - light.wardrobe_light
          - light.bulb
        title: Light
      - type: media-control
        entity: media_player.bedroom
      - type: media-control
        entity: media_player.bedroom_firestick
      - type: media-control
        entity: media_player.kitchen_display
      - type: media-control
        entity: media_player.living_room_mini
      - type: media-control
        entity: media_player.living_room_sonos
      - type: media-control
        entity: media_player.office_sonos
      - type: media-control
        entity: media_player.playstation_4
      - type: media-control
        entity: media_player.shield
      - type: media-control
        entity: media_player.shield_2
      - type: media-control
        entity: media_player.shieldtv
      - type: media-control
        entity: media_player.samsungtv_0a21fe80_00aa_1000_baa5_4844f773bd26
      - type: media-control
        entity: media_player.speakers
      - type: entities
        entities:
          - remote.broadlink
        title: Remote
      - type: entities
        entities:
          - scene.bedroom_relax
        title: Scene
      - type: entities
        entities:
          - script.1591217778391
          - script.1591217664809
          - script.1590180099980
          - script.1591217607638
          - script.1591217907229
          - script.1591218055748
          - script.1591217377878
        title: Script
      - type: entities
        entities:
          - switch.android_debug_bridge
          - switch.bazarr
          - switch.bitwarden
          - switch.code_server
          - switch.esphome
          - switch.glances
          - switch.healthchecks
          - switch.home_assistant
          - switch.letsencrypt
          - switch.mariadb
          - switch.mosquitto
          - switch.nzbget
          - switch.node_red
          - switch.switch
          - switch.plex
          - switch.radarr
          - switch.sonarr
          - switch.tautulli
          - switch.wled_nightlight
          - switch.wled_sync_receive
          - switch.wled_sync_send
          - switch.icloudpd_matt
        title: Switch
      - type: weather-forecast
        entity: weather.home
